### ISSUE TITLE
Specify port on docker 

### ISSUE THREAD

**Issue by yuksbg** [GyunerZeki/easymail#2]
Hi,

Please give example of docker configuration like: 

base image, which ports must be mapped  and etc.

**Comment by GyunerZeki** [comment]
Easymail can work on clean ubuntu:14.04 image as well as phusion/baseimage.
The ports must be opened are 110, 25, 995, 80, 443, 587, 993, 143

Also based on your suggestion README.md file was updated. 
You can check it at 3d4472a03091d21cdbe5f351c219d780db06d1f4

Thanks.

**Comment by kopax** [comment]
This example does not include data persistence and backup, data will be lost on docker container restart.

**Comment by GyunerZeki** [comment]
Hi @kopax 

Yes, script doesn't include backup, but after container restart data will not be lost if you use the example code (there is no **-d** parameter).
