### ISSUE TITLE
PHP is already installed, installation aborted

### ISSUE THREAD

**Issue by kultz** [GyunerZeki/EasyMail#20]
What is this suppose to mean?
```
root@server:~/easymail# bash install.sh 
PHP is already installed, installation aborted
```

**Comment by GyunerZeki** [comment]
Hi @kultz, this means that you have installed PHP already. By default, Ubuntu doesn't come with PHP, probably you installed PHP directly or other package installed it as a dependency.  In the requirement, you can see "Fresh installed Debian or Ubuntu server" is required. 

You have two options:
- remove PHP from your machine.
- install EasyMail over Docker.

Please let me know if anything else bothers you or you just need more information, happy to help.
